services:
  fmd:
    # Use the prebuilt image
    image: registry.gitlab.com/fmd-foss/fmd-server:0.14.0
    # Or build the image yourself (note the leading 'v')
    # build: https://gitlab.com/fmd-foss/fmd-server.git#v0.14.0
    container_name: fmd
    # ports:
    #   - "127.0.0.1:8080:8080"
    volumes:
        - fmd-db:/var/lib/fmd-server/db/
    restart: unless-stopped
    read_only: true
    cap_drop: [ALL]
    security_opt: [no-new-privileges]
    networks:
      - web-net
volumes:
  fmd-db:

networks:
  web-net:
    external: true
