services:
  # Reverse proxy
  caddy:
    image: caddy:latest
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2283:2283"
      - "2283:2283/udp"
    volumes:
      - caddy_data:/data
      - ./conf:/etc/caddy
      - caddy_config:/config
    networks:
      - web-net
    environment:
      # Caddyfile env vars
      EMAIL: ${EMAIL?error}
      PASSWORD_HASH: ${PASSWORD_HASH?error}

volumes:
  caddy_data:
  caddy_config:
    
networks:
  web-net:
    external: true
